# Generated by Django 5.0.6 on 2025-01-05 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Aadhar_Number', models.CharField(max_length=20, unique=True)),
                ('Father_Aadhar_Number', models.CharField(max_length=20, null=True)),
                ('Mother_Aadhar_Number', models.CharField(max_length=20, null=True)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Street', models.CharField(max_length=200)),
                ('Area', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Postal_Code', models.CharField(max_length=20)),
                ('Mobile_Number', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Enrollment_Date', models.DateField()),
                ('Last_Updated', models.DateField()),
                ('Is_Active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'aadharcard',
            },
        ),
        migrations.CreateModel(
            name='PostgresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profiles', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('USER', 'User'), ('PO', 'Police Officer')], default='USER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100, null=True)),
                ('Last_Name', models.CharField(max_length=100, null=True)),
                ('Policy_No', models.CharField(max_length=100, null=True)),
                ('Provider', models.CharField(max_length=100, null=True)),
                ('Valid_Until', models.DateField(null=True)),
                ('Certificate_No', models.CharField(max_length=100, null=True)),
                ('Street', models.CharField(max_length=200, null=True)),
                ('Area', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('Postal_Code', models.CharField(max_length=20, null=True)),
                ('Mobile_Number', models.CharField(max_length=12, null=True)),
                ('Registration_Date', models.DateField(null=True)),
                ('Registration_Expiry', models.DateField(null=True)),
                ('Engine_No', models.CharField(max_length=20, null=True)),
                ('Chassis_No', models.CharField(max_length=20, null=True)),
                ('Engine_Capacity', models.IntegerField(null=True)),
                ('Seating_Capacity', models.IntegerField(null=True)),
                ('Color', models.CharField(max_length=20, null=True)),
                ('Year_of_Manufacture', models.DateField(null=True)),
                ('Make_Model', models.CharField(max_length=50, null=True)),
                ('Vehicle_Class', models.CharField(max_length=50, null=True)),
                ('Vehicle_Type', models.CharField(max_length=50, null=True)),
                ('Fuel_Type', models.CharField(max_length=50, null=True)),
                ('RC_No', models.CharField(max_length=20, null=True)),
                ('License_Plate_No', models.CharField(max_length=20, null=True)),
                ('Is_Active', models.BooleanField(default=True, null=True)),
                ('Aadhar_Number', models.ForeignKey(db_column='Aadhar_Number', on_delete=django.db.models.deletion.CASCADE, to='users.person', to_field='Aadhar_Number')),
            ],
            options={
                'db_table': 'vehicle_data',
            },
        ),
        migrations.CreateModel(
            name='Echallan_main',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Vehicle_No', models.CharField(max_length=255)),
                ('Owner_First_Name', models.CharField(max_length=255)),
                ('Owner_Last_Name', models.CharField(max_length=255)),
                ('Vehicle_Class', models.CharField(max_length=255)),
                ('Chassis_No', models.CharField(max_length=255)),
                ('Engine_No', models.CharField(max_length=255)),
                ('Make_Model', models.CharField(max_length=255)),
                ('Violation_Date', models.DateField()),
                ('Challan_Date', models.DateField()),
                ('Place_Of_Violation', models.TextField()),
                ('Driver_First_Name', models.CharField(max_length=255)),
                ('Driver_Last_Name', models.CharField(max_length=255)),
                ('Driving_license_No', models.CharField(max_length=255)),
                ('Driver_Contact_No', models.CharField(max_length=255)),
                ('Driver_Father_First_Name', models.CharField(max_length=255)),
                ('Driver_Father_Last_Name', models.CharField(max_length=255)),
                ('FineAmount', models.IntegerField(null=True)),
                ('ViolationType', models.CharField(null=True)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.vehicle')),
            ],
            options={
                'db_table': 'echallan_main',
            },
        ),
    ]
