# Generated by Django 5.0.6 on 2025-01-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_resolutionstatus_echallanquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='echallanquery',
            name='ticket_no',
            field=models.CharField(default=1, editable=False, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
