# Generated by Django 5.0.6 on 2025-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_echallanquery_ticket_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='echallan_main',
            name='document_url',
            field=models.TextField(blank=True, null=True, verbose_name='Document URL'),
        ),
    ]
