# Generated by Django 5.0.6 on 2025-03-02 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echallanquery',
            name='document_url',
            field=models.TextField(blank=True, null=True, verbose_name='Document URL'),
        ),
        migrations.AlterField(
            model_name='echallanquery',
            name='echallan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='users.echallan_main', verbose_name='E-Challan'),
        ),
        migrations.AlterField(
            model_name='echallanquery',
            name='issue_type',
            field=models.TextField(blank=True, null=True, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='echallanquery',
            name='query_description',
            field=models.TextField(blank=True, null=True, verbose_name='Query Description'),
        ),
        migrations.AlterField(
            model_name='echallanquery',
            name='resolution_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.resolutionstatus', verbose_name='Resolution Status'),
        ),
        migrations.AlterField(
            model_name='echallanquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
