# Generated by Django 5.0.6 on 2025-03-03 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_echallanquery_document_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EchallanVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('violated_rule', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('echallan_status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated')], default='pending', max_length=20)),
                ('proof_image1', models.ImageField(upload_to='proof_images/')),
                ('proof_image2', models.ImageField(upload_to='proof_images/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
