# Generated by Django 5.0.6 on 2025-03-05 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_echallanverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=50, unique=True)),
                ('station_name', models.CharField(max_length=255)),
                ('assigned_area', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('rank', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='police_officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
