# Generated by Django 5.0.6 on 2025-03-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_policeofficer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeofficer',
            name='assigned_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policeofficer',
            name='station_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
