# Generated by Django 5.0.6 on 2025-04-27 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_policeofficer_assigned_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echallan_main',
            name='document_url',
            field=models.TextField(blank=True, null=True, verbose_name='Document URL'),
        ),
        migrations.AddField(
            model_name='echallan_main',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('e_challan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='users.echallan_main')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
